name: Deploy
on: [push]
jobs:
  Deploy:

    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_HOOK: ${{secrets.CLOUDFLARE_HOOK}}
      B2_APPLICATION_KEY: ${{secrets.B2_APPLICATION_KEY}}
      B2_APPLICATION_KEY_ID: ${{secrets.B2_APPLICATION_KEY_ID}}

    defaults:
      run:
        shell: bash

    steps:

      - name: 🛒 Checkout Code
        uses: actions/checkout@v2

      - name: 🛒 Checkout Fonts
        uses: actions/checkout@v2
        with:
          repository: harishneit/fonts
          token: ${{ secrets.FONTS_TOKEN }}
          path: fonts

      - name: 🚚 Update Cache
        run: |
          sudo apt update -y

      - name: 📦 Install Dependencies
        run: |
          sudo apt install -y fontconfig python3-pip texlive-xetex

      - name: 📦 Install Dependencies
        run: |
          sudo pip install b2

      - name: 🚚 Update Font Cache
        working-directory: ${{ github.workspace }}
        run: |
          sudo cp -rf fonts/otf/*/* /usr/local/share/fonts/ && sudo fc-cache -fv

      - name: 🛠️ Compile Resume
        working-directory: ${{ github.workspace }}
        run: |
          xelatex resume

      - name: ☁️ Upload to B2
        working-directory: ${{ github.workspace }}
        run: |
          b2 upload-file harisht-me resume.pdf resume/resume.pdf

      - name: ⏱️ Wait for 5 mins
        run: |
          sleep 300
      
      - name: 🎯 Trigger Deployment
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CLOUDFLARE_HOOK}"